image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

build_script:
  - cmd: dotnet --version
  - cmd: msbuild --version
  - cmd: msbuild .\HelpExplorerSolution.sln -t:Rebuild -p:Configuration=Release